app = 'reservalink'
primary_region = 'gru'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "on"
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.domains]]
name = "reservalink.site"

[[http_service.domains]]
name = "www.reservalink.site"

[[vm]]
size = 'shared-cpu-1x'
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
